min_version = "2024.9.5"

# install to arch linux
# paru -S cmake         # cmake version 4.0.1-dirty
# paru -S dtc           # DTC v1.7.2-1-gac324a9


[env]
# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[tools]
python = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"             # mise r i
run = '''
python -m ensurepip
wd=$PWD
# -------------------------
echo "*** install west"
pip install --upgrade pip
yes | pip install west
# west init ./zephyr-proj
# cd ./zephyr-proj && west update && west zephyr-export
# cd $wd
# pip install -r ./zephyr-proj/zephyr/scripts/requirements.txt
# -------------------------
echo "*** install zmk"
cd $wd
git clone https://github.com/zmkfirmware/zmk.git
cd zmk
[ ! -d app ] && mkdir app/
west init -l app/
west update
west zephyr-export
pip install -r zephyr/scripts/requirements.txt
# -------------------------
echo "*** install zephyr sdk"
cd ~
wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_linux-x86_64.tar.xz
wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/sha256.sum | shasum --check --ignore-missing
tar xvf zephyr-sdk-0.16.3_linux-x86_64.tar.xz
cd zephyr-sdk-0.16.3
./setup.sh
# -------------------------
# echo "*** install udev rules to flashing"
# sudo cp ~/zephyr-sdk-0.16.3/sysroots/x86_64-pokysdk-linux/usr/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
# sudo udevadm control --reload

echo "done"
'''
