manifest:
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dynamic-pinctl-spi
      remote: hidsh
      revision: main
  self:
    path: config
